2023-06-08 13:59:20,922 INFO    StreamThr :59498 [internal.py:wandb_internal():86] W&B internal server running at pid: 59498, started at: 2023-06-08 13:59:20.921708
2023-06-08 13:59:20,924 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: status
2023-06-08 13:59:20,933 INFO    WriterThread:59498 [datastore.py:open_for_write():85] open: /Users/aysanaghazadeh/University/Pitt/Research/Milos/wave_form_data/ECG_PPG_project/classification/wandb/run-20230608_135920-1jzw1ecb/run-1jzw1ecb.wandb
2023-06-08 13:59:20,934 DEBUG   SenderThread:59498 [sender.py:send():375] send: header
2023-06-08 13:59:20,934 DEBUG   SenderThread:59498 [sender.py:send():375] send: run
2023-06-08 13:59:21,230 INFO    SenderThread:59498 [dir_watcher.py:__init__():219] watching files in: /Users/aysanaghazadeh/University/Pitt/Research/Milos/wave_form_data/ECG_PPG_project/classification/wandb/run-20230608_135920-1jzw1ecb/files
2023-06-08 13:59:21,230 INFO    SenderThread:59498 [sender.py:_start_run_threads():1124] run started: 1jzw1ecb with start time 1686247160.921485
2023-06-08 13:59:21,230 DEBUG   SenderThread:59498 [sender.py:send_request():402] send_request: summary_record
2023-06-08 13:59:21,230 INFO    SenderThread:59498 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-06-08 13:59:21,233 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: check_version
2023-06-08 13:59:21,233 DEBUG   SenderThread:59498 [sender.py:send_request():402] send_request: check_version
2023-06-08 13:59:21,423 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: run_start
2023-06-08 13:59:21,437 DEBUG   HandlerThread:59498 [system_info.py:__init__():31] System info init
2023-06-08 13:59:21,437 DEBUG   HandlerThread:59498 [system_info.py:__init__():46] System info init done
2023-06-08 13:59:21,438 INFO    HandlerThread:59498 [system_monitor.py:start():181] Starting system monitor
2023-06-08 13:59:21,438 INFO    SystemMonitor:59498 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-06-08 13:59:21,439 INFO    HandlerThread:59498 [system_monitor.py:probe():201] Collecting system info
2023-06-08 13:59:21,440 DEBUG   HandlerThread:59498 [system_info.py:probe():195] Probing system
2023-06-08 13:59:21,440 INFO    SystemMonitor:59498 [interfaces.py:start():190] Started cpu monitoring
2023-06-08 13:59:21,441 INFO    SystemMonitor:59498 [interfaces.py:start():190] Started disk monitoring
2023-06-08 13:59:21,442 INFO    SystemMonitor:59498 [interfaces.py:start():190] Started memory monitoring
2023-06-08 13:59:21,442 INFO    SystemMonitor:59498 [interfaces.py:start():190] Started network monitoring
2023-06-08 13:59:21,455 DEBUG   HandlerThread:59498 [git.py:repo():40] git repository is invalid
2023-06-08 13:59:21,455 DEBUG   HandlerThread:59498 [system_info.py:probe():240] Probing system done
2023-06-08 13:59:21,455 DEBUG   HandlerThread:59498 [system_monitor.py:probe():210] {'os': 'macOS-10.16-x86_64-i386-64bit', 'python': '3.9.16', 'heartbeatAt': '2023-06-08T17:59:21.440263', 'startedAt': '2023-06-08T17:59:20.902319', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/aysanaghazadeh/University/Pitt/Research/Milos/wave_form_data/ECG_PPG_project/classification/main.py', 'codePath': 'main.py', 'host': 'Aysans-MacBook-Pro-2.local', 'username': 'aysanaghazadeh', 'executable': '/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 2400, 'min': 2400, 'max': 2400}, 'cpu_freq_per_core': [{'current': 2400, 'min': 2400, 'max': 2400}], 'disk': {'total': 460.4317207336426, 'used': 11.979625701904297}, 'memory': {'total': 16.0}}
2023-06-08 13:59:21,455 INFO    HandlerThread:59498 [system_monitor.py:probe():211] Finished collecting system info
2023-06-08 13:59:21,455 INFO    HandlerThread:59498 [system_monitor.py:probe():214] Publishing system info
2023-06-08 13:59:21,455 DEBUG   HandlerThread:59498 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-06-08 13:59:21,456 DEBUG   HandlerThread:59498 [system_info.py:_save_pip():67] Saving pip packages done
2023-06-08 13:59:21,456 DEBUG   HandlerThread:59498 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-06-08 13:59:22,246 INFO    Thread-17 :59498 [dir_watcher.py:_on_file_created():278] file/dir created: /Users/aysanaghazadeh/University/Pitt/Research/Milos/wave_form_data/ECG_PPG_project/classification/wandb/run-20230608_135920-1jzw1ecb/files/wandb-summary.json
2023-06-08 13:59:22,247 INFO    Thread-17 :59498 [dir_watcher.py:_on_file_created():278] file/dir created: /Users/aysanaghazadeh/University/Pitt/Research/Milos/wave_form_data/ECG_PPG_project/classification/wandb/run-20230608_135920-1jzw1ecb/files/requirements.txt
2023-06-08 13:59:22,248 INFO    Thread-17 :59498 [dir_watcher.py:_on_file_created():278] file/dir created: /Users/aysanaghazadeh/University/Pitt/Research/Milos/wave_form_data/ECG_PPG_project/classification/wandb/run-20230608_135920-1jzw1ecb/files/conda-environment.yaml
2023-06-08 13:59:23,095 DEBUG   HandlerThread:59498 [system_info.py:_save_conda():86] Saving conda packages done
2023-06-08 13:59:23,097 INFO    HandlerThread:59498 [system_monitor.py:probe():216] Finished publishing system info
2023-06-08 13:59:23,101 DEBUG   SenderThread:59498 [sender.py:send():375] send: files
2023-06-08 13:59:23,102 INFO    SenderThread:59498 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-06-08 13:59:23,110 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: stop_status
2023-06-08 13:59:23,111 DEBUG   SenderThread:59498 [sender.py:send_request():402] send_request: stop_status
2023-06-08 13:59:23,238 INFO    Thread-17 :59498 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/aysanaghazadeh/University/Pitt/Research/Milos/wave_form_data/ECG_PPG_project/classification/wandb/run-20230608_135920-1jzw1ecb/files/conda-environment.yaml
2023-06-08 13:59:23,238 INFO    Thread-17 :59498 [dir_watcher.py:_on_file_created():278] file/dir created: /Users/aysanaghazadeh/University/Pitt/Research/Milos/wave_form_data/ECG_PPG_project/classification/wandb/run-20230608_135920-1jzw1ecb/files/wandb-metadata.json
2023-06-08 13:59:23,271 DEBUG   SenderThread:59498 [sender.py:send():375] send: telemetry
2023-06-08 13:59:23,310 DEBUG   SenderThread:59498 [sender.py:send():375] send: telemetry
2023-06-08 13:59:23,541 DEBUG   SenderThread:59498 [sender.py:send():375] send: telemetry
2023-06-08 13:59:23,543 INFO    wandb-upload_0:59498 [upload_job.py:push():137] Uploaded file /var/folders/1t/6l04b1413h7_m7f246431wmc0000gn/T/tmp1qf7s2yrwandb/rwisas1l-wandb-metadata.json
2023-06-08 13:59:24,255 DEBUG   SenderThread:59498 [sender.py:send():375] send: telemetry
2023-06-08 13:59:25,246 INFO    Thread-17 :59498 [dir_watcher.py:_on_file_created():278] file/dir created: /Users/aysanaghazadeh/University/Pitt/Research/Milos/wave_form_data/ECG_PPG_project/classification/wandb/run-20230608_135920-1jzw1ecb/files/output.log
2023-06-08 13:59:26,245 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: status_report
2023-06-08 13:59:27,263 INFO    Thread-17 :59498 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/aysanaghazadeh/University/Pitt/Research/Milos/wave_form_data/ECG_PPG_project/classification/wandb/run-20230608_135920-1jzw1ecb/files/output.log
2023-06-08 13:59:31,270 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: status_report
2023-06-08 13:59:36,286 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: status_report
2023-06-08 13:59:38,122 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: stop_status
2023-06-08 13:59:38,124 DEBUG   SenderThread:59498 [sender.py:send_request():402] send_request: stop_status
2023-06-08 13:59:42,234 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: status_report
2023-06-08 13:59:47,255 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: status_report
2023-06-08 13:59:52,279 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: status_report
2023-06-08 13:59:52,375 ERROR   SenderThread:59498 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-06-08 13:59:52,375 ERROR   SenderThread:59498 [internal_api.py:execute():289] {"errors":[{"message":"run aysan/ecg_classification/1jzw1ecb was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-06-08 13:59:53,673 ERROR   SenderThread:59498 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-06-08 13:59:53,674 ERROR   SenderThread:59498 [internal_api.py:execute():289] {"errors":[{"message":"run aysan/ecg_classification/1jzw1ecb was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-06-08 13:59:53,747 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: poll_exit
2023-06-08 13:59:55,818 ERROR   SenderThread:59498 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-06-08 13:59:55,818 ERROR   SenderThread:59498 [internal_api.py:execute():289] {"errors":[{"message":"run aysan/ecg_classification/1jzw1ecb was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-06-08 13:59:55,819 INFO    SenderThread:59498 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-06-08 13:59:58,769 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:00:00,530 ERROR   SenderThread:59498 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-06-08 14:00:00,530 ERROR   SenderThread:59498 [internal_api.py:execute():289] {"errors":[{"message":"run aysan/ecg_classification/1jzw1ecb was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-06-08 14:00:03,792 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:00:08,813 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:00:09,403 ERROR   SenderThread:59498 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-06-08 14:00:09,403 ERROR   SenderThread:59498 [internal_api.py:execute():289] {"errors":[{"message":"run aysan/ecg_classification/1jzw1ecb was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-06-08 14:00:13,834 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:00:18,857 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:00:21,448 DEBUG   SystemMonitor:59498 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-06-08 14:00:23,879 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:00:26,515 ERROR   SenderThread:59498 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-06-08 14:00:26,516 ERROR   SenderThread:59498 [internal_api.py:execute():289] {"errors":[{"message":"run aysan/ecg_classification/1jzw1ecb was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-06-08 14:00:28,902 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:00:33,926 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:00:38,953 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:00:43,981 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:00:49,005 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:00:54,027 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:00:59,054 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:01:04,080 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:01:04,160 ERROR   SenderThread:59498 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-06-08 14:01:04,160 ERROR   SenderThread:59498 [internal_api.py:execute():289] {"errors":[{"message":"run aysan/ecg_classification/1jzw1ecb was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-06-08 14:01:09,100 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:01:14,120 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:01:19,142 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:01:24,164 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:01:29,193 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:01:34,216 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:01:39,237 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:01:44,259 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:01:49,283 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:01:54,309 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:01:59,332 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:02:04,357 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:02:09,380 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:02:14,398 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:02:19,425 DEBUG   HandlerThread:59498 [handler.py:handle_request():144] handle_request: keepalive
2023-06-08 14:02:20,588 ERROR   SenderThread:59498 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-06-08 14:02:20,589 ERROR   SenderThread:59498 [internal_api.py:execute():289] {"errors":[{"message":"run aysan/ecg_classification/1jzw1ecb was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-06-08 14:02:20,602 INFO    WriterThread:59498 [datastore.py:close():298] close: /Users/aysanaghazadeh/University/Pitt/Research/Milos/wave_form_data/ECG_PPG_project/classification/wandb/run-20230608_135920-1jzw1ecb/run-1jzw1ecb.wandb
2023-06-08 14:02:21,436 INFO    HandlerThread:59498 [handler.py:finish():842] shutting down handler
2023-06-08 14:02:21,437 INFO    HandlerThread:59498 [system_monitor.py:finish():190] Stopping system monitor
2023-06-08 14:02:21,438 DEBUG   SystemMonitor:59498 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-06-08 14:02:21,440 INFO    HandlerThread:59498 [interfaces.py:finish():202] Joined cpu monitor
2023-06-08 14:02:21,441 DEBUG   SystemMonitor:59498 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-06-08 14:02:21,442 INFO    HandlerThread:59498 [interfaces.py:finish():202] Joined disk monitor
2023-06-08 14:02:21,445 INFO    HandlerThread:59498 [interfaces.py:finish():202] Joined memory monitor
2023-06-08 14:02:21,446 INFO    HandlerThread:59498 [interfaces.py:finish():202] Joined network monitor
2023-06-08 14:02:21,447 ERROR   StreamThr :59498 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1690, in upsert_run
    response = self.gql(
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 257, in gql
    ret = self._retry_gql(
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 334, in _debounce
    self._sm.debounce()
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 551, in debounce
    self._maybe_update_config(always=final)
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 528, in _maybe_update_config
    self._debounce_config()
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 557, in _debounce_config
    self._api.upsert_run(
  File "/Users/aysanaghazadeh/opt/anaconda3/envs/ECG_PPG_project/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run aysan/ecg_classification/1jzw1ecb was previously created and deleted; try a new run name (Error 409: Conflict)
